name: Challenge-3

on: [push]


jobs:
    job1:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: step one
              uses: actions/checkout@v2
            - name: step two
              run: python3 hello.py
    job2:
        name: build
        runs-on: ubuntu-latest
        needs: [job1]
        steps:
            - name: step one
              uses: actions/checkout@v2
            - name: Upload artifact
              uses: actions/upload-artifact@v2
              with:
                name: Hello
                path: .